---
networks:
  default: mainnet-fork

  mainnet-fork:
    cmd_settings:
      unlock: # accounts order is crucial!
        - 0x834560F580764Bc2e0B16925F8bF229bb00cB759 # manager
        - 0x3e40D73EB977Dc6a537aF587D48316feE66E9C8c # owner
  holesky-fork:
    cmd_settings:
      unlock: # accounts order is crucial!
        - 0x96d2Ff1C4D30f592B91fd731E218247689a76915 # manager
        - 0xE92329EC7ddB11D25e25b3c21eeBf11f15eB325d # owner

compiler:
  evm_version: berlin
  vyper:
    version: 0.3.7
