live:
  - name: Ethereum
    networks:
      - chainid: 560048
        explorer: https://api-hoodi.etherscan.io/api
        host: https://hoodi.infura.io/v3/$WEB3_INFURA_PROJECT_ID
        id: hoodi
        # multicall2 is missing on Hoodi. New backward-compatible multicall contract.
        # See https://github.com/mds1/multicall
        multicall2: "0xcA11bde05977b3631167028862bE2a173976CA11"
        name: Hoodi (Infura)

development:
  - cmd: ganache-cli
    cmd_settings:
      fork: mainnet
      port: 8545
    host: http://127.0.0.1
    id: mainnet-fork
    name: Ganache-CLI (Mainnet Fork)
    timeout: 360
    # https://github.com/mds1/multicall#multicall2-contract-addresses
    multicall2: "0x5BA1e12693Dc8F9c48aAD8770482f4739bEeD696"

  - cmd: ganache-cli
    cmd_settings:
      fork: holesky
      port: 8545
    host: http://127.0.0.1
    id: holesky-fork
    name: Ganache-CLI (Holesky Fork)
    timeout: 360
    # New backward-compatible multicall contract. multicall2 is missing on Holesky. See https://github.com/mds1/multicall
    multicall2: "0xcA11bde05977b3631167028862bE2a173976CA11"

  - cmd: ganache-cli
    cmd_settings:
      fork: hoodi
      port: 8545
    host: http://127.0.0.1
    id: hoodi-fork
    name: Ganache-CLI (Hoodi Fork)
    timeout: 360
    # New backward-compatible multicall contract. multicall2 is missing on Holesky. See https://github.com/mds1/multicall
    multicall2: "0xcA11bde05977b3631167028862bE2a173976CA11"